### ISSUE TITLE
Provide more configurability around git checkout

### ISSUE THREAD

**Issue by rnowosielski** [Cimpress-MCP/JustReleaseNotes#25]
Apparently there are a lot of places where both `origin` and `master` are hardcoded, but this assumption is not correct.

In my case

```
Git: Retrieving Git history...
Traceback (most recent call last):
  File "/usr/local/bin/just_release", line 9, in <module>
    load_entry_point('JustReleaseNotes==0.1.2', 'console_scripts', 'just_release')()
  File "/Library/Python/2.7/site-packages/JustReleaseNotes/command_line.py", line 53, in main
    releaseNotes = generator.generateReleaseNotesByPromotedVersions()
  File "/Library/Python/2.7/site-packages/JustReleaseNotes/releaseNotes.py", line 45, in generateReleaseNotesByPromotedVersions
    self.__repo.retrieveHistory()
  File "/Library/Python/2.7/site-packages/JustReleaseNotes/sourcers/GitRepo.py", line 87, in retrieveHistory
    for i in self.__repoX.iter_commits('master', max_count=1024):
  File "/Library/Python/2.7/site-packages/git/objects/commit.py", line 265, in _iter_from_process_or_stream
    finalize_process(proc_or_stream)
  File "/Library/Python/2.7/site-packages/git/util.py", line 154, in finalize_process
    proc.wait()
  File "/Library/Python/2.7/site-packages/git/cmd.py", line 309, in wait
    raise GitCommandError(self.args, status, self.proc.stderr.read())
git.exc.GitCommandError: 'git rev-list --max-count=1024 master --' returned with exit code 128
stderr: 'fatal: bad revision 'master'
```

I don't have a branch called master and none of my remotes is called origin.

**Comment by rnowosielski** [comment]
This should be resolved
