### ISSUE TITLE
Incremental generation fails when non-ASCII characters are present

### ISSUE THREAD

**Issue by mmaruniak** [Cimpress-MCP/JustReleaseNotes#49]
There seems to be an inconsistency with reading and writing files containing non-ASCII characters. This results in errors when a previously saved file is read, e.g. during incremental generation.

**Comment by mmaruniak** [comment]
Example stack trace:

Traceback (most recent call last):
  File "C:\Python27\Scripts\just_release-script.py", line 9, in <module>
    load_entry_point('JustReleaseNotes==0.1.8', 'console_scripts', 'just_release')()
  File "C:\Python27\lib\site-packages\justreleasenotes-0.1.8-py2.7.egg\JustReleaseNotes\command_line.py", line 26, in main
    generate_release_notes(args.config)
  File "C:\Python27\lib\site-packages\justreleasenotes-0.1.8-py2.7.egg\JustReleaseNotes\command_line.py", line 88, in generate_re
lease_notes
    generateForOneWriter(generator, ticketProvider, writerConfigs, directory, None)
  File "C:\Python27\lib\site-packages\justreleasenotes-0.1.8-py2.7.egg\JustReleaseNotes\command_line.py", line 48, in generateFor
OneWriter
    f.write(releaseNotes.encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 15418: ordinal not in range(128)

**Comment by rnowosielski** [comment]
@mmaruniak could you attach an example of the non-ASCII character that caused this - I would add it as a unit test and work from there

**Comment by mmaruniak** [comment]
For example: ı

**Comment by rnowosielski** [comment]
It should be fixed in the next version. If by any chance it doesn't work you might care to update the unit/integ test  `test_givenUnicodeCharacterInTheInitialContent_DoesntFail` with the failing example - that way we can at least figure out what is failing
